import * as XLSX from 'xlsx';
import pptxgen from 'pptxgenjs';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, WidthType, BorderStyle } from 'docx';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { ChatMessage } from '../types';

export interface BusinessReportData {
  title: string;
  author: string;
  company?: string;
  executiveSummary: string;
  financialMetrics: {
    month: string;
    revenue: number;
    cogs: number;
    grossProfit: number;
    opex: number;
    netIncome: number;
    marginPct: number;
  }[];
  regionalData: {
    region: string;
    revenue: number;
    growthPct: number;
    marketSharePct: number;
    headcount: number;
  }[];
  recommendations: string[];
}

export const sampleBusinessReport: BusinessReportData = {
  title: 'Q3 Enterprise Performance & Strategic Growth Analysis',
  author: 'farhee intelligent 2.0 Analytics Engine',
  company: 'Global Intelligence Corp',
  executiveSummary:
    'During the preceding fiscal cycle, enterprise initiatives yielded a 24.8% YoY net income surge, led by AI infrastructure automation and cloud database optimization. Operating leverage expanded by 340 bps while customer retention reached 98.4%.',
  financialMetrics: [
    { month: 'January', revenue: 145000, cogs: 42000, grossProfit: 103000, opex: 51000, netIncome: 52000, marginPct: 35.8 },
    { month: 'February', revenue: 158000, cogs: 44000, grossProfit: 114000, opex: 53000, netIncome: 61000, marginPct: 38.6 },
    { month: 'March', revenue: 172000, cogs: 47000, grossProfit: 125000, opex: 55000, netIncome: 70000, marginPct: 40.7 },
    { month: 'April', revenue: 184000, cogs: 49000, grossProfit: 135000, opex: 57000, netIncome: 78000, marginPct: 42.4 },
    { month: 'May', revenue: 196000, cogs: 51000, grossProfit: 145000, opex: 59000, netIncome: 86000, marginPct: 43.8 },
    { month: 'June', revenue: 215000, cogs: 53000, grossProfit: 162000, opex: 61000, netIncome: 101000, marginPct: 47.0 },
  ],
  regionalData: [
    { region: 'North America', revenue: 425000, growthPct: 28.5, marketSharePct: 42.0, headcount: 142 },
    { region: 'EMEA', revenue: 310000, growthPct: 22.1, marketSharePct: 29.5, headcount: 96 },
    { region: 'Asia-Pacific', revenue: 245000, growthPct: 34.7, marketSharePct: 21.0, headcount: 88 },
    { region: 'Latin America', revenue: 90000, growthPct: 18.3, marketSharePct: 7.5, headcount: 34 },
  ],
  recommendations: [
    'Scale real-time telemetry pipelines to streamline multi-region transaction latency.',
    'Consolidate zero-trust encryption protocols across all customer touchpoints.',
    'Deploy automated Last-Write-Wins conflict resolution models for decentralized sales nodes.',
    'Capitalize on high-margin APAC enterprise demand with localized AI interfaces.',
  ],
};

/**
 * 1. Excel Spreadsheet Export (.xlsx)
 * Multi-tab comprehensive workbook with formatted columns and totals
 */
export async function exportToExcel(data: BusinessReportData = sampleBusinessReport): Promise<Blob> {
  const wb = XLSX.utils.book_new();

  // Tab 1: Executive Dashboard Summary
  const summarySheetData = [
    ['FARHEE INTELLIGENT 2.0 - EXECUTIVE BUSINESS ANALYSIS REPORT'],
    ['Report Title', data.title],
    ['Generated By', data.author],
    ['Date Generated', new Date().toLocaleDateString()],
    ['Classification', 'CONFIDENTIAL // INTERNAL BUSINESS DATA'],
    [],
    ['KEY PERFORMANCE INDICATORS (KPIs)'],
    ['Total Analyzed Revenue ($)', data.financialMetrics.reduce((acc, curr) => acc + curr.revenue, 0)],
    ['Total Net Income ($)', data.financialMetrics.reduce((acc, curr) => acc + curr.netIncome, 0)],
    ['Average Profit Margin (%)', (data.financialMetrics.reduce((acc, curr) => acc + curr.marginPct, 0) / data.financialMetrics.length).toFixed(1) + '%'],
    ['Total Global Headcount', data.regionalData.reduce((acc, curr) => acc + curr.headcount, 0)],
    [],
    ['EXECUTIVE NARRATIVE'],
    [data.executiveSummary],
  ];
  const wsSummary = XLSX.utils.aoa_to_sheet(summarySheetData);
  wsSummary['!cols'] = [{ wch: 30 }, { wch: 50 }];
  XLSX.utils.book_append_sheet(wb, wsSummary, 'Executive Summary');

  // Tab 2: Monthly Financial Performance
  const financialRows = data.financialMetrics.map((f) => ({
    Month: f.month,
    'Revenue ($)': f.revenue,
    'COGS ($)': f.cogs,
    'Gross Profit ($)': f.grossProfit,
    'OpEx ($)': f.opex,
    'Net Income ($)': f.netIncome,
    'Margin (%)': f.marginPct + '%',
  }));
  const wsFinancial = XLSX.utils.json_to_sheet(financialRows);
  wsFinancial['!cols'] = [{ wch: 15 }, { wch: 16 }, { wch: 14 }, { wch: 16 }, { wch: 14 }, { wch: 16 }, { wch: 14 }];
  XLSX.utils.book_append_sheet(wb, wsFinancial, 'Monthly Financials');

  // Tab 3: Regional Analysis
  const regionalRows = data.regionalData.map((r) => ({
    Region: r.region,
    'Revenue ($)': r.revenue,
    'YoY Growth (%)': r.growthPct + '%',
    'Market Share (%)': r.marketSharePct + '%',
    Headcount: r.headcount,
  }));
  const wsRegional = XLSX.utils.json_to_sheet(regionalRows);
  wsRegional['!cols'] = [{ wch: 20 }, { wch: 18 }, { wch: 16 }, { wch: 18 }, { wch: 14 }];
  XLSX.utils.book_append_sheet(wb, wsRegional, 'Regional Breakdown');

  // Tab 4: Strategic Recommendations
  const recRows = data.recommendations.map((rec, i) => [i + 1, rec]);
  const wsRec = XLSX.utils.aoa_to_sheet([['No.', 'Strategic Initiative / Action Item'], ...recRows]);
  wsRec['!cols'] = [{ wch: 6 }, { wch: 75 }];
  XLSX.utils.book_append_sheet(wb, wsRec, 'Strategic Initiatives');

  const wbout = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
  return new Blob([wbout], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
}

/**
 * 2. PDF Document Export (.pdf)
 * Clean executive design with header, tables, and branding
 */
export async function exportToPdf(data: BusinessReportData = sampleBusinessReport): Promise<Blob> {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  // Top header bar
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, 210, 24, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.text('farhee intelligent 2.0', 14, 15);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184);
  doc.text('Enterprise Intelligence & Strategic Analysis', 130, 15);

  // Document Title
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text(data.title, 14, 38);

  // Metadata line
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(`Generated: ${new Date().toLocaleDateString()} | Author: ${data.author} | Classification: Confidential`, 14, 45);

  // Executive Summary
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text('Executive Summary', 14, 55);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(51, 65, 85);
  const splitSummary = doc.splitTextToSize(data.executiveSummary, 182);
  doc.text(splitSummary, 14, 62);

  const startTableY = 62 + splitSummary.length * 6 + 4;

  // Financial Table
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text('Monthly Financial Performance Model', 14, startTableY);

  autoTable(doc, {
    startY: startTableY + 4,
    head: [['Month', 'Revenue', 'COGS', 'Gross Profit', 'OpEx', 'Net Income', 'Margin']],
    body: data.financialMetrics.map((f) => [
      f.month,
      `$${f.revenue.toLocaleString()}`,
      `$${f.cogs.toLocaleString()}`,
      `$${f.grossProfit.toLocaleString()}`,
      `$${f.opex.toLocaleString()}`,
      `$${f.netIncome.toLocaleString()}`,
      `${f.marginPct}%`,
    ]),
    theme: 'grid',
    headStyles: { fillColor: [30, 41, 59], textColor: [255, 255, 255], fontStyle: 'bold' },
    styles: { fontSize: 8.5, cellPadding: 2.5 },
  });

  // Regional Table
  const finalY = (doc as any).lastAutoTable.finalY || 150;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text('Regional Market Analysis', 14, finalY + 10);

  autoTable(doc, {
    startY: finalY + 14,
    head: [['Region', 'Revenue', 'YoY Growth', 'Market Share', 'Headcount']],
    body: data.regionalData.map((r) => [
      r.region,
      `$${r.revenue.toLocaleString()}`,
      `+${r.growthPct}%`,
      `${r.marketSharePct}%`,
      r.headcount.toString(),
    ]),
    theme: 'striped',
    headStyles: { fillColor: [51, 65, 85], textColor: [255, 255, 255] },
    styles: { fontSize: 8.5, cellPadding: 2.5 },
  });

  // Footer on page
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(
      `farhee intelligent 2.0 Encrypted Business Document • Page ${i} of ${pageCount} • E2EE AES-256-GCM Verified`,
      14,
      287
    );
  }

  return doc.output('blob');
}

/**
 * 3. PowerPoint Presentation Export (.pptx)
 * 5-slide polished business deck
 */
export async function exportToPptx(data: BusinessReportData = sampleBusinessReport): Promise<Blob> {
  const pptx = new pptxgen();
  pptx.layout = 'LAYOUT_16x9';

  // Slide 1: Cover
  const s1 = pptx.addSlide();
  s1.background = { color: '0F172A' };
  s1.addText('farhee intelligent 2.0', {
    x: 1.0,
    y: 1.2,
    fontSize: 16,
    color: '38BDF8',
    bold: true,
  });
  s1.addText(data.title, {
    x: 1.0,
    y: 1.8,
    w: 11.0,
    fontSize: 32,
    color: 'FFFFFF',
    bold: true,
  });
  s1.addText(`Prepared by: ${data.author} | ${new Date().toLocaleDateString()}`, {
    x: 1.0,
    y: 3.4,
    fontSize: 14,
    color: '94A3B8',
  });
  s1.addShape(pptx.ShapeType.rect, {
    x: 1.0,
    y: 4.8,
    w: 4.5,
    h: 0.8,
    fill: { color: '1E293B' },
    line: { color: '38BDF8', width: 1 },
  });
  s1.addText('CONFIDENTIAL // BUSINESS ANALYSIS', {
    x: 1.2,
    y: 5.0,
    fontSize: 11,
    color: '38BDF8',
    bold: true,
  });

  // Slide 2: Executive Summary & Highlights
  const s2 = pptx.addSlide();
  s2.background = { color: 'FFFFFF' };
  s2.addText('Executive Summary & Strategic Overview', {
    x: 0.8,
    y: 0.6,
    fontSize: 22,
    bold: true,
    color: '0F172A',
  });
  s2.addText(data.executiveSummary, {
    x: 0.8,
    y: 1.4,
    w: 11.5,
    fontSize: 14,
    color: '334155',
    lineSpacing: 22,
  });

  // 3 KPI Metric Cards
  const totalRev = data.financialMetrics.reduce((a, b) => a + b.revenue, 0);
  const totalNet = data.financialMetrics.reduce((a, b) => a + b.netIncome, 0);

  s2.addShape(pptx.ShapeType.roundRect, { x: 0.8, y: 3.2, w: 3.6, h: 2.2, fill: { color: 'F8FAFC' }, line: { color: 'E2E8F0' } });
  s2.addText('Total Revenue', { x: 1.0, y: 3.5, fontSize: 13, color: '64748B' });
  s2.addText(`$${(totalRev / 1000).toFixed(0)}K`, { x: 1.0, y: 4.0, fontSize: 28, bold: true, color: '0F172A' });
  s2.addText('↑ +28.4% YoY Growth', { x: 1.0, y: 4.8, fontSize: 11, color: '10B981', bold: true });

  s2.addShape(pptx.ShapeType.roundRect, { x: 4.8, y: 3.2, w: 3.6, h: 2.2, fill: { color: 'F8FAFC' }, line: { color: 'E2E8F0' } });
  s2.addText('Net Income', { x: 5.0, y: 3.5, fontSize: 13, color: '64748B' });
  s2.addText(`$${(totalNet / 1000).toFixed(0)}K`, { x: 5.0, y: 4.0, fontSize: 28, bold: true, color: '0F172A' });
  s2.addText('Operating margin: 41.2%', { x: 5.0, y: 4.8, fontSize: 11, color: '3B82F6', bold: true });

  s2.addShape(pptx.ShapeType.roundRect, { x: 8.8, y: 3.2, w: 3.6, h: 2.2, fill: { color: 'F8FAFC' }, line: { color: 'E2E8F0' } });
  s2.addText('Global Headcount', { x: 9.0, y: 3.5, fontSize: 13, color: '64748B' });
  s2.addText('360 FTE', { x: 9.0, y: 4.0, fontSize: 28, bold: true, color: '0F172A' });
  s2.addText('Across 4 Global Regions', { x: 9.0, y: 4.8, fontSize: 11, color: '8B5CF6', bold: true });

  // Slide 3: Financial Performance Breakdown
  const s3 = pptx.addSlide();
  s3.background = { color: 'FFFFFF' };
  s3.addText('Monthly Financial Analysis (H1)', { x: 0.8, y: 0.6, fontSize: 22, bold: true, color: '0F172A' });

  const tableRows: any[] = [
    [
      { text: 'Month', options: { bold: true, color: 'FFFFFF', fill: { color: '1E293B' } } },
      { text: 'Revenue', options: { bold: true, color: 'FFFFFF', fill: { color: '1E293B' } } },
      { text: 'Gross Profit', options: { bold: true, color: 'FFFFFF', fill: { color: '1E293B' } } },
      { text: 'OpEx', options: { bold: true, color: 'FFFFFF', fill: { color: '1E293B' } } },
      { text: 'Net Income', options: { bold: true, color: 'FFFFFF', fill: { color: '1E293B' } } },
      { text: 'Margin %', options: { bold: true, color: 'FFFFFF', fill: { color: '1E293B' } } },
    ],
    ...data.financialMetrics.map((m) => [
      m.month,
      `$${m.revenue.toLocaleString()}`,
      `$${m.grossProfit.toLocaleString()}`,
      `$${m.opex.toLocaleString()}`,
      `$${m.netIncome.toLocaleString()}`,
      `${m.marginPct}%`,
    ]),
  ];

  s3.addTable(tableRows, {
    x: 0.8,
    y: 1.4,
    w: 11.6,
    colW: [2.0, 2.0, 2.0, 1.8, 2.0, 1.8],
    fontSize: 11,
    border: { pt: 1, color: 'E2E8F0' },
  });

  // Slide 4: Recommendations & Action Items
  const s4 = pptx.addSlide();
  s4.background = { color: 'FFFFFF' };
  s4.addText('Strategic Recommendations & Execution Roadmap', { x: 0.8, y: 0.6, fontSize: 22, bold: true, color: '0F172A' });

  data.recommendations.forEach((rec, idx) => {
    s4.addShape(pptx.ShapeType.roundRect, {
      x: 0.8,
      y: 1.4 + idx * 1.2,
      w: 11.6,
      h: 0.95,
      fill: { color: 'F8FAFC' },
      line: { color: 'CBD5E1' },
    });
    s4.addText(`0${idx + 1}`, {
      x: 1.0,
      y: 1.6 + idx * 1.2,
      fontSize: 16,
      bold: true,
      color: '3B82F6',
    });
    s4.addText(rec, {
      x: 1.6,
      y: 1.65 + idx * 1.2,
      w: 10.4,
      fontSize: 13,
      color: '1E293B',
    });
  });

  return (await pptx.write({ outputType: 'blob' })) as Blob;
}

/**
 * 4. Word Document Export (.docx)
 * Structured report with tables, heading styles, and executive sign-off
 */
export async function exportToDocx(data: BusinessReportData = sampleBusinessReport): Promise<Blob> {
  const doc = new Document({
    sections: [
      {
        properties: {},
        children: [
          new Paragraph({
            text: data.title,
            heading: HeadingLevel.TITLE,
            spacing: { after: 200 },
          }),
          new Paragraph({
            children: [
              new TextRun({ text: 'Author: ', bold: true }),
              new TextRun(data.author),
              new TextRun({ text: '  |  Date: ', bold: true }),
              new TextRun(new Date().toLocaleDateString()),
              new TextRun({ text: '  |  Security: ', bold: true }),
              new TextRun('E2EE AES-256-GCM Verified (farhee intelligent 2.0)'),
            ],
            spacing: { after: 400 },
          }),
          new Paragraph({
            text: '1. Executive Summary',
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 200, after: 150 },
          }),
          new Paragraph({
            text: data.executiveSummary,
            spacing: { after: 300 },
          }),
          new Paragraph({
            text: '2. Monthly Financial Performance',
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 200, after: 150 },
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: ['Month', 'Revenue ($)', 'COGS ($)', 'Gross Profit ($)', 'Net Income ($)', 'Margin (%)'].map(
                  (header) =>
                    new TableCell({
                      children: [new Paragraph({ children: [new TextRun({ text: header, bold: true })] })],
                      borders: {
                        top: { style: BorderStyle.SINGLE, size: 1, color: 'CBD5E1' },
                        bottom: { style: BorderStyle.SINGLE, size: 1, color: 'CBD5E1' },
                        left: { style: BorderStyle.NONE },
                        right: { style: BorderStyle.NONE },
                      },
                    })
                ),
              }),
              ...data.financialMetrics.map(
                (f) =>
                  new TableRow({
                    children: [
                      f.month,
                      `$${f.revenue.toLocaleString()}`,
                      `$${f.cogs.toLocaleString()}`,
                      `$${f.grossProfit.toLocaleString()}`,
                      `$${f.netIncome.toLocaleString()}`,
                      `${f.marginPct}%`,
                    ].map(
                      (val) =>
                        new TableCell({
                          children: [new Paragraph(val)],
                          borders: {
                            top: { style: BorderStyle.SINGLE, size: 1, color: 'F1F5F9' },
                            bottom: { style: BorderStyle.SINGLE, size: 1, color: 'F1F5F9' },
                            left: { style: BorderStyle.NONE },
                            right: { style: BorderStyle.NONE },
                          },
                        })
                    ),
                  })
              ),
            ],
          }),
          new Paragraph({
            text: '3. Strategic Recommendations',
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 400, after: 150 },
          }),
          ...data.recommendations.map(
            (rec, idx) =>
              new Paragraph({
                children: [
                  new TextRun({ text: `${idx + 1}. `, bold: true }),
                  new TextRun(rec),
                ],
                spacing: { after: 100 },
              })
          ),
          new Paragraph({
            text: 'Sign-off & Approval',
            heading: HeadingLevel.HEADING_2,
            spacing: { before: 400, after: 100 },
          }),
          new Paragraph({
            children: [
              new TextRun({ text: 'Executive Signee: ________________________   Date: ___________' }),
            ],
          }),
        ],
      },
    ],
  });

  return await Packer.toBlob(doc);
}

export interface ExportConversationPdfOptions {
  sessionTitle: string;
  messages: ChatMessage[];
  userName?: string;
  language?: string;
}

/**
 * Generates an executive-formatted PDF containing the full conversation history
 * from the current session with structured styling, sender badges, and timestamps.
 */
export async function exportConversationToPdf({
  sessionTitle,
  messages,
  userName = 'Shahfiya',
  language = 'en',
}: ExportConversationPdfOptions): Promise<Blob> {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;

  // Header Cover Banner
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(margin, 14, pageWidth - margin * 2, 38, 'F');

  // Decorative cyan accent stripe
  doc.setFillColor(56, 189, 248); // sky-400
  doc.rect(margin, 14, 3.5, 38, 'F');

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(255, 255, 255);
  doc.text('Farhee Intelligent 2.0', margin + 8, 24);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(186, 230, 253); // sky-200
  const cleanSessionTitle = (sessionTitle || 'Conversation Session').slice(0, 48);
  doc.text(`Conversation Transcript: ${cleanSessionTitle}`, margin + 8, 32);

  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184); // slate-400
  const exportDate = new Date().toLocaleString();
  doc.text(
    `Exported: ${exportDate} • Messages: ${messages.length} • Security: Client-Side AES-256-GCM Vault`,
    margin + 8,
    42
  );

  // Metadata summary card
  doc.setFillColor(248, 250, 252); // slate-50
  doc.setDrawColor(226, 232, 240); // slate-200
  doc.rect(margin, 56, pageWidth - margin * 2, 18, 'FD');

  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(51, 65, 85);
  doc.text('Participants:', margin + 4, 62);
  doc.setFont('helvetica', 'normal');
  doc.text(`${userName} (User)  &  Farhee Intelligent 2.0 (Personal AI Collaborator)`, margin + 28, 62);

  doc.setFont('helvetica', 'bold');
  doc.text('Session Scope:', margin + 4, 69);
  doc.setFont('helvetica', 'normal');
  doc.text(`Language: ${(language || 'en').toUpperCase()} • Multi-turn Dialogue • Verified Transcript`, margin + 28, 69);

  // Format message rows for autoTable
  const tableRows = messages.map((m, idx) => {
    const isUser = m.sender === 'user';
    const speakerLabel = isUser ? `${userName}` : 'Farhee Intelligent 2.0';
    const timestampStr = new Date(m.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

    // Clean text: strip markdown syntax cleanly for elegant printable rendering
    const cleanText = m.text
      .replace(/^###\s+/gm, '')
      .replace(/^##\s+/gm, '')
      .replace(/^#\s+/gm, '')
      .replace(/\*\*([^*]+)\*\*/g, '$1')
      .replace(/\*([^*]+)\*/g, '$1')
      .replace(/`([^`]+)`/g, '$1')
      .trim();

    const attachmentSummary = m.attachments && m.attachments.length > 0
      ? `\n\n[Attached File(s): ${m.attachments.map((a) => a.name).join(', ')}]`
      : '';

    return [
      `#${idx + 1}`,
      speakerLabel,
      timestampStr,
      cleanText + attachmentSummary,
    ];
  });

  autoTable(doc, {
    startY: 78,
    head: [['#', 'Sender', 'Time', 'Transcript Content']],
    body: tableRows.length > 0 ? tableRows : [['-', 'System', '-', 'No messages recorded in this session.']],
    theme: 'grid',
    headStyles: {
      fillColor: [30, 41, 59], // Slate 800
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8.5,
      cellPadding: 3,
    },
    styles: {
      fontSize: 8.5,
      cellPadding: 3.5,
      overflow: 'linebreak',
      textColor: [15, 23, 42],
    },
    columnStyles: {
      0: { cellWidth: 10, halign: 'center', fontStyle: 'bold', textColor: [100, 116, 139] },
      1: { cellWidth: 38, fontStyle: 'bold' },
      2: { cellWidth: 22, fontSize: 7.5, textColor: [100, 116, 139] },
      3: { cellWidth: 'auto' },
    },
    didParseCell: (data) => {
      if (data.section === 'body') {
        const rowIndex = data.row.index;
        const msg = messages[rowIndex];
        if (msg) {
          if (msg.sender === 'assistant') {
            data.cell.styles.fillColor = [248, 250, 252]; // Light sky-slate tint
            if (data.column.index === 1) {
              data.cell.styles.textColor = [2, 132, 199]; // Sky 600
            }
          } else {
            data.cell.styles.fillColor = [255, 255, 255];
            if (data.column.index === 1) {
              data.cell.styles.textColor = [15, 23, 42]; // Slate 900
            }
          }
        }
      }
    },
    margin: { left: margin, right: margin, bottom: 20 },
  });

  // Footer on every page
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    // Header thin rule
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.3);
    doc.line(margin, 10, pageWidth - margin, 10);

    doc.setFontSize(7.5);
    doc.setTextColor(148, 163, 184);
    doc.text('farhee intelligent 2.0 • Personal AI Collaborator', margin, 7.5);
    doc.text(cleanSessionTitle.slice(0, 40), pageWidth - margin, 7.5, { align: 'right' });

    // Footer line
    doc.line(margin, pageHeight - 12, pageWidth - margin, pageHeight - 12);
    doc.text(
      'Encrypted Session Transcript • Zero-Knowledge Local Vault Verified • Confidential',
      margin,
      pageHeight - 7
    );
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, pageHeight - 7, { align: 'right' });
  }

  return doc.output('blob');
}

/**
 * Ensures a clean, professional watermark reading "Farhee Intelligent 2.0"
 * is stamped onto the bottom-right corner of an image.
 */
export async function applyWatermarkToImageDataUrl(
  imageUrl: string,
  watermarkText = 'Farhee Intelligent 2.0'
): Promise<string> {
  if (!imageUrl) return imageUrl;

  return new Promise((resolve) => {
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = () => {
      try {
        const canvas = document.createElement('canvas');
        canvas.width = img.naturalWidth || img.width || 800;
        canvas.height = img.naturalHeight || img.height || 800;
        const ctx = canvas.getContext('2d');
        if (!ctx) {
          resolve(imageUrl);
          return;
        }

        // Draw the base image
        ctx.drawImage(img, 0, 0, canvas.width, canvas.height);

        // Calculate responsive watermark size based on canvas dimensions
        const fontSize = Math.max(12, Math.min(22, Math.round(canvas.width * 0.024)));
        ctx.font = `600 ${fontSize}px -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif`;
        const textMetrics = ctx.measureText(watermarkText);

        const padX = Math.round(fontSize * 0.75);
        const padY = Math.round(fontSize * 0.45);
        const iconSize = Math.round(fontSize * 0.7);
        const pillWidth = textMetrics.width + padX * 2 + iconSize + 6;
        const pillHeight = fontSize + padY * 2;
        const margin = Math.round(fontSize * 0.9);

        const pillX = canvas.width - pillWidth - margin;
        const pillY = canvas.height - pillHeight - margin;

        ctx.save();
        // Subtle semi-transparent dark pill background
        ctx.fillStyle = 'rgba(15, 23, 42, 0.78)';
        ctx.strokeStyle = 'rgba(255, 255, 255, 0.28)';
        ctx.lineWidth = 1;

        const radius = pillHeight / 2;
        ctx.beginPath();
        ctx.moveTo(pillX + radius, pillY);
        ctx.lineTo(pillX + pillWidth - radius, pillY);
        ctx.arcTo(pillX + pillWidth, pillY, pillX + pillWidth, pillY + radius, radius);
        ctx.lineTo(pillX + pillWidth, pillY + pillHeight - radius);
        ctx.arcTo(pillX + pillWidth, pillY + pillHeight, pillX + pillWidth - radius, pillY + pillHeight, radius);
        ctx.lineTo(pillX + radius, pillY + pillHeight);
        ctx.arcTo(pillX, pillY + pillHeight, pillX, pillY + pillHeight - radius, radius);
        ctx.lineTo(pillX, pillY + radius);
        ctx.arcTo(pillX, pillY, pillX + radius, pillY, radius);
        ctx.closePath();
        ctx.fill();
        ctx.stroke();

        // Accent glowing cyan dot
        ctx.fillStyle = '#38bdf8';
        ctx.beginPath();
        ctx.arc(pillX + padX + iconSize / 2, pillY + pillHeight / 2, iconSize / 2.5, 0, Math.PI * 2);
        ctx.fill();

        // Watermark text
        ctx.fillStyle = '#ffffff';
        ctx.textBaseline = 'middle';
        ctx.fillText(watermarkText, pillX + padX + iconSize + 6, pillY + pillHeight / 2);
        ctx.restore();

        resolve(canvas.toDataURL('image/png'));
      } catch (err) {
        console.warn('Watermark canvas error:', err);
        resolve(imageUrl);
      }
    };

    img.onerror = () => resolve(imageUrl);
    img.src = imageUrl;
  });
}
